travis:
  secure:
    BINSTAR_TOKEN: hhSiiYfU/tFzE/pE8xJIGWbhDesQAW1fpqlm4/Cgu4vZrmLbSueKy334rh1Ig7/ZjDGhYQF7Ran173uRZwidiOlyxzUbr5QWpZVi/LY1JaCPiST7Iej66sN51WmbGe4OygB9Unc0zk5SpK1PvIHFDjYHtHsuw6jR4GPJZl+9ApRcWFJRbjuCmK+c4tUYKtbfQXT/rOLH+HejoNvmt5QImOR8OV3TQ36B5wEJhZHrWTunM9/qPBJ0S+r6yBNOKV3ywyxFwtKv4oZjSFAJgK1ilkCZ2fwb5UeU0d+3dzerMrL68ogg+9cRyq+8fDekUvnYjVON5Vgh1l0Sk13l7Y6gj/daRpZnK5OZXk1O4YaalK4BZ+fIWeKV8eZsGx3LsApT3evzGtg5eE2x63sBsfcWUJGwlDKDnZoEyoiJOPl/vTM61Mx+F436M7C7in15sdJJYHbovvmQP2Davs+MfTImm1vEK5hnHodhd7VBHULnd5hETGji5qXi8T5Xgafi1H9RVxtI4VjwQI6xRkPBz5BWW1yHYDVZk6R2acJDCDp/oRJT1di84OyilQisTfGDhaNvOP9j/xKhyMXgCK6SSV+7yP0YBGo1sG5yV2A3thcfV9ScCk8hEMVfnnKuCdufwVLRFVpyCJP4+OCquiJ/B83qURBZx5CTwk+QO2PwOCwx77o=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
